"""
Django settings for iErp project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# CARGAR EL ARCHIVO .ENV
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Usa os.environ.get para leer la variable del .env
SECRET_KEY = os.environ.get('SECRET_KEY', 'una-llave-temporal-por-si-falla-el-env')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost').split(',')

# Dominio base de la plataforma SaaS. Si está vacío (dev), no hay scoping por
# subdominio. En prod: BASE_DOMAIN=ierp.mx → cada cliente vive en <slug>.ierp.mx.
BASE_DOMAIN = os.environ.get('BASE_DOMAIN', '').strip()

# Detrás de Traefik (HTTPS): confía en el proto reenviado y en los orígenes https.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = [
    f"https://{h.strip()}" for h in ALLOWED_HOSTS
    if h.strip() and h.strip() not in ('localhost', '127.0.0.1')
]
if BASE_DOMAIN:
    CSRF_TRUSTED_ORIGINS.append(f"https://*.{BASE_DOMAIN}")


# URL base del sitio — usada en correos cuando no hay request disponible
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8005').rstrip('/')

# Proxy HTTPS — Nginx le pasa X-Forwarded-Proto a Django
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# En producción con HTTPS activo, Django confía en el header del proxy
USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    'unfold',  # <--- Debe ir arriba de django.contrib.admin
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'admon_empresas',
    'admon_usuarios',
    'admon_inventarios',
    'admon_produccion',
    'admon_compras',
    'admon_finanzas',
    'admon_ventas',
    'admon_cirugias',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'admon_empresas.middleware.TenantMiddleware',
    'admon_empresas.middleware.ModuloAccessMiddleware',
    'iErp.middleware.TimezoneMiddleware',
]

ROOT_URLCONF = 'iErp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Para templates globales (opcional)
        'APP_DIRS': True,                 # <--- ESTO DEBE ESTAR EN TRUE
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',                
                'admon_empresas.context_processors.empresa_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'iErp.wsgi.application'

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql', 
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASS'),
        'HOST': os.environ.get('DB_HOST'), # Sin la IP aquí
        'PORT': os.environ.get('DB_PORT', '1433'),
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'TrustServerCertificate=yes;Encrypt=no', 
            'connection_timeout': 30,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = 'static/'

# Esto es vital para que Django busque en la carpeta que creamos
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Esta carpeta es la que usa Docker para servir en "producción"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# WhiteNoise sirve los estáticos comprimidos en producción (sin manifest para
# no romper si una plantilla referencia un estático ausente).
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

# Ruta donde se guardarán los archivos subidos (logos, etc)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

UNFOLD = {
    "SITE_TITLE": "iErp Global Admin",
    "SITE_HEADER": "iErp Cloud Management",
    "SITE_SYMBOL": "speed", # Icono de Material Symbols
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "500": "168 85 247", # El color morado/azul de un SaaS
            "600": "147 51 234",
            "900": "88 28 135",
        },
    },
}

# EMAIL CONFIGURATION — Resend API HTTP (no requiere puertos SMTP abiertos)
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'TI Grupo Gonza <ti@phanalytics.com.mx>')
