# Generated by Django 5.2.15 on 2026-06-16 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admon_empresas', '0002_impuesto'),
        ('admon_inventarios', '0004_remove_detallereceta_insumo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20)),
                ('cantidad_a_producir', models.DecimalField(decimal_places=4, max_digits=12)),
                ('cantidad_producida', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_PROCESO', 'En proceso'), ('PAUSADA', 'Pausada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='ABIERTA', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_empresas.empresa')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_empresas.sucursal')),
            ],
            options={
                'verbose_name_plural': 'Órdenes de producción',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(decimal_places=4, max_digits=12)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.producto')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.lote')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.numeroserie')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.ubicacion')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='admon_produccion.ordenproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('rendimiento', models.DecimalField(decimal_places=4, default=1, help_text='Unidades de producto terminado que produce esta receta', max_digits=12)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_empresas.empresa')),
                ('producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='admon_inventarios.producto')),
            ],
            options={
                'unique_together': {('producto_terminado', 'version')},
            },
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_produccion.receta'),
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=4, max_digits=12)),
                ('es_opcional', models.BooleanField(default=False)),
                ('notas', models.CharField(blank=True, max_length=255, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_recetas', to='admon_inventarios.producto')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='admon_produccion.receta')),
            ],
        ),
    ]
