# Generated by Django 5.2.15 on 2026-07-28 16:39

import admon_comunes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admon_empresas', '0011_perfilusuario_foto'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('archivo', models.FileField(max_length=500, upload_to=admon_comunes.models.ruta_adjunto)),
                ('nombre_original', models.CharField(max_length=255, verbose_name='Nombre')),
                ('extension', models.CharField(blank=True, max_length=12)),
                ('mime_detectado', models.CharField(blank=True, max_length=120)),
                ('tamano_bytes', models.BigIntegerField(default=0)),
                ('hash_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('es_imagen', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, max_length=500, null=True, upload_to=admon_comunes.models.ruta_adjunto)),
                ('estado_scan', models.CharField(choices=[('PEND', 'Pendiente de análisis'), ('LIMPIO', 'Limpio'), ('INFECTADO', 'Infectado'), ('ERROR', 'Error al analizar')], default='PEND', max_length=9)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='admon_empresas.empresa')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
                'db_table': 'comunes_adjunto',
                'ordering': ('-subido_en',),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='comunes_adj_content_5f18fb_idx'), models.Index(fields=['empresa', 'subido_en'], name='comunes_adj_empresa_499640_idx')],
            },
        ),
    ]
