# Generated by Django 5.2.15 on 2026-08-07 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_comunes', '0001_initial'),
        ('admon_empresas', '0011_perfilusuario_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ASIGNACION', 'Asignación'), ('COMENTARIO', 'Comentario'), ('ESTADO', 'Cambio de estado'), ('BLOQUEO', 'Bloqueo'), ('GENERAL', 'General')], default='GENERAL', max_length=12)),
                ('titulo', models.CharField(max_length=180)),
                ('mensaje', models.CharField(blank=True, max_length=500)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('icono', models.CharField(blank=True, max_length=30)),
                ('leida', models.BooleanField(default=False)),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_generadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='admon_empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comunes_notificacion',
                'ordering': ('-creada_en',),
                'indexes': [models.Index(fields=['usuario', 'leida'], name='comunes_not_usuario_8b9b93_idx'), models.Index(fields=['usuario', '-creada_en'], name='comunes_not_usuario_a6af96_idx')],
            },
        ),
    ]
