# Generated by Django 5.2.15 on 2026-06-13 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admon_empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_empresas.empresa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacenes', to='admon_empresas.sucursal')),
            ],
            options={
                'verbose_name_plural': 'Almacenes',
                'unique_together': {('sucursal', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_empresas.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
                ('es_inventariable', models.BooleanField(default=True, help_text='¿Este grupo genera movimientos de stock?')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_empresas.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='InstanciaKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_caja', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_PREPARACION', 'En preparación'), ('EN_CAMPO', 'En campo (hospital)'), ('RETORNADA', 'Retornada (pendiente revisión)'), ('REABASTECIENDO', 'Reabasteciendo'), ('BAJA', 'Dada de baja')], default='DISPONIBLE', max_length=15)),
                ('notas', models.TextField(blank=True, null=True)),
                ('sucursal_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_empresas.sucursal')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instancias', to='admon_inventarios.kit')),
            ],
            options={
                'verbose_name_plural': 'Instancias de kit (cajas)',
                'unique_together': {('kit', 'codigo_caja')},
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Código interno', max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo_barras', models.CharField(blank=True, help_text='EAN/UPC', max_length=50, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('alcance', models.CharField(choices=[('GLOBAL', 'Global (todas las sucursales)'), ('SUCURSAL', 'Por sucursal (solo asignadas)')], default='GLOBAL', max_length=10)),
                ('es_loteable', models.BooleanField(default=False, help_text='¿Maneja número de lote y caducidad?')),
                ('es_serializable', models.BooleanField(default=False, help_text='¿Maneja números de serie únicos?')),
                ('es_comprable', models.BooleanField(default=True, help_text='¿Se puede comprar a proveedores?')),
                ('es_vendible', models.BooleanField(default=True, help_text='¿Se puede vender a clientes?')),
                ('es_materia_prima', models.BooleanField(default=False, help_text='¿Es insumo para producción?')),
                ('es_producible', models.BooleanField(default=False, help_text='¿Se fabrica mediante una receta/BOM?')),
                ('es_retornable', models.BooleanField(default=False, help_text='¿Es herramienta/préstamo que regresa? (kits)')),
                ('registro_sanitario', models.CharField(blank=True, max_length=100, null=True)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('precio_venta', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.clase')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='admon_empresas.empresa')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='NumeroSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_KIT', 'Asignada a kit en campo'), ('VENDIDA', 'Vendida / consumida'), ('EN_TRANSITO', 'En tránsito (traspaso)'), ('BAJA', 'Dada de baja')], default='DISPONIBLE', max_length=15)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='admon_inventarios.producto')),
            ],
            options={
                'unique_together': {('producto', 'serie')},
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100)),
                ('fecha_fabricacion', models.DateField(blank=True, null=True)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='admon_inventarios.producto')),
            ],
            options={
                'unique_together': {('producto', 'numero_lote')},
            },
        ),
        migrations.CreateModel(
            name='DetalleKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=4, max_digits=12)),
                ('es_retornable', models.BooleanField(default=False, help_text='True = herramienta/préstamo que siempre regresa. False = consumible que puede usarse.')),
                ('notas', models.CharField(blank=True, max_length=255, null=True)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='admon_inventarios.kit')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.producto')),
            ],
        ),
        migrations.CreateModel(
            name='RecepcionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20)),
                ('proveedor_nombre', models.CharField(blank=True, help_text='Para recepciones directas sin OC', max_length=255, null=True)),
                ('remision_proveedor', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_empresas.empresa')),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_empresas.sucursal')),
            ],
            options={
                'verbose_name_plural': 'Recepciones de material',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.DecimalField(decimal_places=4, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.producto')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='admon_inventarios.recepcionmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('rendimiento', models.DecimalField(decimal_places=4, default=1, help_text='Unidades de producto terminado que produce esta receta', max_digits=12)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_empresas.empresa')),
                ('producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='admon_inventarios.producto')),
            ],
            options={
                'unique_together': {('producto_terminado', 'version')},
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20)),
                ('cantidad_a_producir', models.DecimalField(decimal_places=4, max_digits=12)),
                ('cantidad_producida', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_PROCESO', 'En proceso'), ('PAUSADA', 'Pausada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='ABIERTA', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_empresas.empresa')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_empresas.sucursal')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.receta')),
            ],
            options={
                'verbose_name_plural': 'Órdenes de producción',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=4, max_digits=12)),
                ('es_opcional', models.BooleanField(default=False)),
                ('notas', models.CharField(blank=True, max_length=255, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_recetas', to='admon_inventarios.producto')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='admon_inventarios.receta')),
            ],
        ),
        migrations.CreateModel(
            name='SalidaKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20)),
                ('hospital_cliente', models.CharField(max_length=255)),
                ('doctor_responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_cirugia', models.CharField(blank=True, max_length=50, null=True)),
                ('paciente_referencia', models.CharField(blank=True, help_text='Referencia interna, no datos sensibles', max_length=100, null=True)),
                ('estado', models.CharField(choices=[('PREPARANDO', 'Preparando'), ('ENVIADA', 'Enviada'), ('EN_USO', 'En uso'), ('RETORNADA', 'Retornada'), ('CERRADA', 'Cerrada (usado facturado/vendido)'), ('CANCELADA', 'Cancelada')], default='PREPARANDO', max_length=15)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('fecha_retorno_esperada', models.DateField(blank=True, null=True)),
                ('fecha_retorno_real', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas_kit_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_empresas.empresa')),
                ('instancia_kit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='admon_inventarios.instanciakit')),
                ('retorno_procesado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retornos_kit_procesados', to=settings.AUTH_USER_MODEL)),
                ('sucursal_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_empresas.sucursal')),
            ],
            options={
                'verbose_name_plural': 'Salidas de kit',
                'ordering': ['-fecha_salida'],
            },
        ),
        migrations.CreateModel(
            name='SerieRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_recibidas', to='admon_inventarios.detallerecepcion')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.numeroserie')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudTraspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('EN_TRANSITO', 'En tránsito'), ('RECIBIDO', 'Recibido'), ('RECIBIDO_PARCIAL', 'Recibido parcial'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('notas_solicitud', models.TextField(blank=True, null=True)),
                ('notas_envio', models.TextField(blank=True, null=True)),
                ('notas_recepcion', models.TextField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_empresas.empresa')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_enviados', to=settings.AUTH_USER_MODEL)),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_solicitados', to=settings.AUTH_USER_MODEL)),
                ('sucursal_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_entrantes', to='admon_empresas.sucursal')),
                ('sucursal_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_salientes', to='admon_empresas.sucursal')),
            ],
            options={
                'verbose_name_plural': 'Solicitudes de traspaso',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='DetalleTraspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=4, max_digits=12)),
                ('cantidad_enviada', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('cantidad_recibida', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.producto')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='admon_inventarios.solicitudtraspaso')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_empresas.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.tipo'),
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='admon_inventarios.almacen')),
            ],
            options={
                'verbose_name_plural': 'Ubicaciones',
                'unique_together': {('almacen', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='TrazabilidadTraspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trazabilidad', to='admon_inventarios.detalletraspaso')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.lote')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.numeroserie')),
                ('ubicacion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.ubicacion')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion_defecto',
            field=models.ForeignKey(blank=True, help_text='Opcional. Si se deja vacío, usará la del Grupo.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon_inventarios.ubicacion'),
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE_POS', 'Ajuste positivo'), ('AJUSTE_NEG', 'Ajuste negativo'), ('TRASPASO_SAL', 'Traspaso - salida'), ('TRASPASO_ENT', 'Traspaso - entrada'), ('KIT_SALIDA', 'Kit - salida a campo'), ('KIT_RETORNO', 'Kit - retorno de campo'), ('KIT_CONSUMO', 'Kit - consumido en cirugía'), ('PROD_CONSUMO', 'Producción - consumo de insumo'), ('PROD_ENTRADA', 'Producción - entrada de terminado'), ('VENTA', 'Venta / consumo')], max_length=15)),
                ('origen', models.CharField(choices=[('RECEPCION', 'Recepción de material'), ('OC', 'Orden de compra'), ('TRASPASO', 'Traspaso entre sucursales'), ('PRODUCCION', 'Orden de producción'), ('KIT', 'Salida de kit'), ('AJUSTE', 'Ajuste manual'), ('VENTA', 'Venta')], max_length=15)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.almacen')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_empresas.empresa')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.lote')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_empresas.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.numeroserie')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='admon_inventarios.producto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.ubicacion')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='ubicacion_defecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_predeterminados', to='admon_inventarios.ubicacion'),
        ),
        migrations.AddField(
            model_name='detalletraspaso',
            name='ubicacion_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_recibidos', to='admon_inventarios.ubicacion'),
        ),
        migrations.AddField(
            model_name='detallerecepcion',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.ubicacion'),
        ),
        migrations.CreateModel(
            name='ContenidoSalidaKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_retornable', models.BooleanField(default=False)),
                ('cantidad_enviada', models.DecimalField(decimal_places=4, max_digits=12)),
                ('cantidad_retornada', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('cantidad_usada', models.DecimalField(decimal_places=4, default=0, help_text='enviada - retornada (lo que se factura)', max_digits=12)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.lote')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.numeroserie')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.producto')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenido', to='admon_inventarios.salidakit')),
                ('ubicacion_origen', models.ForeignKey(help_text='De dónde se tomó (y a dónde regresa lo no usado)', on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(decimal_places=4, max_digits=12)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.lote')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.numeroserie')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='admon_inventarios.ordenproduccion')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.producto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_empresas.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.unidadmedida'),
        ),
        migrations.CreateModel(
            name='ProductoSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo_en_sucursal', models.BooleanField(default=True)),
                ('precio_venta_override', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('costo_unitario_override', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('stock_minimo', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('stock_maximo', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('punto_reorden', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_sucursales', to='admon_inventarios.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_config', to='admon_empresas.sucursal')),
            ],
            options={
                'verbose_name_plural': 'Productos por sucursal',
                'unique_together': {('producto', 'sucursal')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_inventarios.almacen')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_empresas.sucursal')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admon_inventarios.lote')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admon_inventarios.numeroserie')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_inventarios.producto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_inventarios.ubicacion')),
            ],
            options={
                'unique_together': {('producto', 'ubicacion', 'lote', 'serie')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('empresa', 'sku')},
        ),
    ]
