# Generated by Django 5.2.15 on 2026-06-13 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_compras', '0001_initial'),
        ('admon_inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerecepcion',
            name='detalle_oc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='admon_compras.detalleordencompra'),
        ),
        migrations.AddField(
            model_name='recepcionmaterial',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='admon_compras.ordencompra'),
        ),
    ]
