# Generated by Django 5.2.15 on 2026-06-13 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresas', '0002_impuesto'),
        ('admon_inventarios', '0002_detallerecepcion_detalle_oc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='impuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='admon_empresas.impuesto'),
        ),
    ]
