# Generated by Django 5.2.15 on 2026-06-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admon_inventarios', '0003_producto_impuesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallereceta',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='detallereceta',
            name='receta',
        ),
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='receta',
        ),
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='sucursal',
        ),
        migrations.AlterUniqueTogether(
            name='receta',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='receta',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='producto_terminado',
        ),
        migrations.DeleteModel(
            name='ConsumoProduccion',
        ),
        migrations.DeleteModel(
            name='DetalleReceta',
        ),
        migrations.DeleteModel(
            name='OrdenProduccion',
        ),
        migrations.DeleteModel(
            name='Receta',
        ),
    ]
