# Generated by Django 5.2.15 on 2026-06-16 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresas', '0005_seed_modulo_ventas'),
        ('admon_inventarios', '0004_remove_detallereceta_insumo_and_more'),
        ('admon_ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidosalidakit',
            name='propiedad',
            field=models.CharField(choices=[('PROPIO', 'Propio'), ('CONSIGNA', 'Consignación')], default='PROPIO', max_length=10),
        ),
        migrations.AddField(
            model_name='existencia',
            name='propiedad',
            field=models.CharField(choices=[('PROPIO', 'Propio'), ('CONSIGNA', 'Consignación')], default='PROPIO', max_length=10),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='propiedad',
            field=models.CharField(choices=[('PROPIO', 'Propio'), ('CONSIGNA', 'Consignación')], default='PROPIO', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_renta',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Tarifa de renta si el producto es retornable/préstamo', max_digits=18),
        ),
        migrations.AddField(
            model_name='salidakit',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_ventas.cliente'),
        ),
        migrations.AddField(
            model_name='salidakit',
            name='pedido_generado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_kit', to='admon_ventas.pedido'),
        ),
        migrations.AddField(
            model_name='salidakit',
            name='propiedad',
            field=models.CharField(choices=[('PROPIO', 'Propio'), ('CONSIGNA', 'Consignación')], default='PROPIO', max_length=10),
        ),
        migrations.CreateModel(
            name='Consignante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rfc', models.CharField(blank=True, max_length=15, null=True)),
                ('contacto', models.CharField(blank=True, max_length=120, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignantes', to='admon_empresas.empresa')),
            ],
            options={
                'verbose_name': 'Consignante',
                'verbose_name_plural': 'Consignantes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='existencia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contenidosalidakit',
            name='consignante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.consignante'),
        ),
        migrations.AddField(
            model_name='existencia',
            name='consignante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.consignante'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='consignante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.consignante'),
        ),
        migrations.AddField(
            model_name='salidakit',
            name='consignante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.consignante'),
        ),
        migrations.AlterUniqueTogether(
            name='existencia',
            unique_together={('producto', 'ubicacion', 'lote', 'serie', 'propiedad', 'consignante')},
        ),
    ]
