# Generated by Django 5.2.15 on 2026-06-17 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_inventarios', '0005_contenidosalidakit_propiedad_existencia_propiedad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanciakit',
            name='ubicacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caja', to='admon_inventarios.ubicacion'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE_POS', 'Ajuste positivo'), ('AJUSTE_NEG', 'Ajuste negativo'), ('TRASPASO_SAL', 'Traspaso - salida'), ('TRASPASO_ENT', 'Traspaso - entrada'), ('KIT_SALIDA', 'Kit - salida a campo'), ('KIT_RETORNO', 'Kit - retorno de campo'), ('KIT_CONSUMO', 'Kit - consumido en cirugía'), ('CAJA_REAB_SAL', 'Caja - salida de almacén (reabasto)'), ('CAJA_REAB_ENT', 'Caja - entrada a caja (reabasto)'), ('PROD_CONSUMO', 'Producción - consumo de insumo'), ('PROD_ENTRADA', 'Producción - entrada de terminado'), ('VENTA', 'Venta / consumo')], max_length=15),
        ),
    ]
