# Generated by Django 5.2.15 on 2026-06-20 18:00

import django.db.models.deletion
from django.db import migrations, models


def backfill_empresa(apps, schema_editor):
    """Las cajas existentes derivan su empresa de la plantilla Kit."""
    InstanciaKit = apps.get_model('admon_inventarios', 'InstanciaKit')
    for caja in InstanciaKit.objects.filter(empresa__isnull=True, kit__isnull=False).select_related('kit'):
        caja.empresa_id = caja.kit.empresa_id
        caja.save(update_fields=['empresa'])


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresas', '0006_seed_modulo_cirugias'),
        ('admon_inventarios', '0006_instanciakit_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instanciakit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='instanciakit',
            name='consignante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='admon_inventarios.consignante'),
        ),
        migrations.AddField(
            model_name='instanciakit',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='admon_empresas.empresa'),
        ),
        migrations.AddField(
            model_name='instanciakit',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre descriptivo de la caja (cajas libres sin plantilla)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instanciakit',
            name='propiedad',
            field=models.CharField(choices=[('PROPIO', 'Propio'), ('CONSIGNA', 'Consignación')], default='PROPIO', max_length=10),
        ),
        migrations.AlterField(
            model_name='instanciakit',
            name='kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instancias', to='admon_inventarios.kit'),
        ),
        migrations.RunPython(backfill_empresa, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='instanciakit',
            unique_together={('empresa', 'codigo_caja')},
        ),
        migrations.CreateModel(
            name='ContenidoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_objetivo', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('es_retornable', models.BooleanField(default=False, help_text='True = herramienta/renta que regresa. False = consumible.')),
                ('notas', models.CharField(blank=True, max_length=255, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='admon_inventarios.instanciakit')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.producto')),
            ],
            options={
                'verbose_name_plural': 'Contenido de cajas',
                'unique_together': {('caja', 'producto')},
            },
        ),
    ]
