# Generated by Django 5.2.15 on 2026-06-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_inventarios', '0007_alter_instanciakit_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='es_uso_personal',
            field=models.BooleanField(default=False, help_text='Destino del stock marcado como uso personal (excluido de reportes y no vendible).'),
        ),
    ]
