# Generated by Django 5.2.15 on 2026-06-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_inventarios', '0008_almacen_es_uso_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='margen',
            field=models.DecimalField(decimal_places=2, default=15, help_text='Margen financiero por defecto (% sobre venta)', max_digits=6),
        ),
    ]
