# Generated by Django 5.2.15 on 2026-07-09 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_inventarios', '0009_producto_margen'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanciakit',
            name='caja_contenedora',
            field=models.ForeignKey(blank=True, help_text='Si esta caja va dentro de otra (ej. una tornillera dentro de la caja de cirugía).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_hijas', to='admon_inventarios.instanciakit'),
        ),
    ]
