# Generated by Django 5.2.15 on 2026-07-16 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_inventarios', '0011_ampliar_codigo_catalogos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidakit',
            name='instancia_kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='admon_inventarios.instanciakit'),
        ),
    ]
