# Generated by Django 5.2.15 on 2026-06-13 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admon_empresas', '0001_initial'),
        ('admon_inventarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=25, unique=True)),
                ('consecutivo', models.IntegerField(default=0)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('SOLICITADO', 'En autorización'), ('AUTORIZADO', 'Autorizado'), ('RECIBIDO', 'Recibido parcial'), ('FINALIZADO', 'Finalizado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('autorizador_actual', models.ForeignKey(blank=True, help_text='Quién tiene la OC para firmar en este momento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_por_autorizar', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_empresas.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_empresas.moneda')),
                ('sucursal_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='admon_empresas.sucursal')),
                ('usuario_cancelacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_canceladas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Órdenes de compra',
                'ordering': ['-fecha_emision', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pedida', models.DecimalField(decimal_places=4, max_digits=12)),
                ('cantidad_recibida', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=16, max_digits=5)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='admon_compras.ordencompra')),
            ],
        ),
        migrations.CreateModel(
            name='AutorizacionOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.PositiveIntegerField(default=1)),
                ('accion', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], max_length=10)),
                ('es_final', models.BooleanField(default=False, help_text='True si esta firma cerró la autorización.')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones', to='admon_compras.ordencompra')),
            ],
            options={
                'ordering': ['secuencia'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fiscal', models.CharField(max_length=255)),
                ('nombre_comercial', models.CharField(blank=True, max_length=255, null=True)),
                ('rfc', models.CharField(max_length=15, verbose_name='RFC / Tax ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('contacto_nombre', models.CharField(blank=True, max_length=100, verbose_name='Atención con')),
                ('dias_credito', models.PositiveIntegerField(default=0, verbose_name='Días de crédito')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='admon_empresas.empresa')),
                ('moneda_predeterminada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon_empresas.moneda')),
                ('sucursales_acceso', models.ManyToManyField(blank=True, related_name='proveedores_permitidos', to='admon_empresas.sucursal')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre_fiscal'],
            },
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_compras.proveedor'),
        ),
        migrations.CreateModel(
            name='AutorizadorCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_autorizado', models.DecimalField(decimal_places=2, default=0, help_text='Monto máximo que puede autorizar. 0 = sin límite (cima de la cadena).', max_digits=14)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizadores_compra', to='admon_empresas.empresa')),
                ('supervisor', models.ForeignKey(blank=True, help_text='A quién escala cuando el monto supera su límite.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados_compra', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones_compra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autorizador de compras',
                'verbose_name_plural': 'Autorizadores de compras',
                'unique_together': {('empresa', 'usuario')},
            },
        ),
    ]
