# Generated by Django 5.2.15 on 2026-06-13 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_compras', '0001_initial'),
        ('admon_empresas', '0002_impuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleordencompra',
            name='es_retencion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='impuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon_empresas.impuesto'),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=4, default=16, max_digits=7),
        ),
    ]
