# Generated by Django 5.2.15 on 2026-06-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_compras', '0002_detalleordencompra_es_retencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
