# Generated by Django 5.2.15 on 2026-06-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_compras', '0003_proveedor_celular_proveedor_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='folio',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
