# Generated by Django 5.2.15 on 2026-06-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_compras', '0004_alter_ordencompra_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='uso_personal',
            field=models.BooleanField(default=False),
        ),
    ]
