# Generated by Django 5.2.15 on 2026-07-28 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admon_empresas', '0011_perfilusuario_foto'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6b7280', max_length=7)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas_tarea', to='admon_empresas.empresa')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'db_table': 'tareas_etiqueta',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('ARRANQUE', 'Arranque'), ('IMPLEMENTACION', 'Implementación'), ('SOPORTE', 'Soporte'), ('MEJORA', 'Mejora'), ('INTERNO', 'Interno')], default='INTERNO', max_length=14)),
                ('modo_cierre', models.CharField(choices=[('TODOS', 'Todos los asignados confirman'), ('RESPONSABLE', 'Solo el responsable cierra'), ('CUALQUIERA', 'El primero que confirme')], default='TODOS', max_length=12)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('color', models.CharField(default='#4f46e5', max_length=7)),
                ('activo', models.BooleanField(default=True)),
                ('es_plantilla', models.BooleanField(default=False, help_text='Un tablero plantilla no se trabaja: sirve de molde para crear otros.', verbose_name='Es plantilla')),
                ('alcance', models.CharField(choices=[('EMPRESA', 'Solo esta empresa'), ('GLOBAL', 'Catálogo del proveedor')], default='EMPRESA', max_length=7)),
                ('instanciado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tableros_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableros', to='admon_empresas.empresa')),
                ('plantilla_origen', models.ForeignKey(blank=True, editable=False, help_text='Plantilla de la que salió este tablero.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instancias', to='admon_tareas.tablero')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tableros_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tablero',
                'verbose_name_plural': 'Tableros',
                'db_table': 'tareas_tablero',
                'ordering': ('nombre',),
                'permissions': [('gestionar_plantillas_globales', 'Puede crear plantillas globales e instanciarlas en cualquier empresa')],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('orden', models.IntegerField(default=0)),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='admon_tareas.tablero')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'db_table': 'tareas_seccion',
                'ordering': ('orden', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, editable=False, max_length=13)),
                ('ruta_wbs', models.CharField(blank=True, default='', editable=False, max_length=60)),
                ('nivel', models.SmallIntegerField(default=0, editable=False)),
                ('orden', models.IntegerField(default=0)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('PROC', 'En proceso'), ('BLOQ', 'Bloqueada'), ('REVI', 'En revisión'), ('COMP', 'Completada'), ('CANC', 'Cancelada')], db_index=True, default='PEND', max_length=4)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGE', 'Urgente')], default='MEDIA', max_length=5)),
                ('perfil_sugerido', models.CharField(blank=True, help_text="Solo se usa en plantillas. Ej: 'Consultor funcional', 'Contacto del cliente'.", max_length=80, verbose_name='Perfil sugerido')),
                ('fecha_inicio_plan', models.DateField(blank=True, null=True)),
                ('fecha_fin_plan', models.DateField(blank=True, null=True)),
                ('fecha_inicio_real', models.DateField(blank=True, null=True)),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('duracion_dias', models.IntegerField(blank=True, null=True)),
                ('avance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('es_hito', models.BooleanField(default=False, verbose_name='Es hito')),
                ('es_resumen', models.BooleanField(default=False, editable=False)),
                ('es_bloqueante', models.BooleanField(default=False, editable=False)),
                ('origen_obj_id', models.PositiveIntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_cerradas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='admon_empresas.empresa')),
                ('etiquetas', models.ManyToManyField(blank=True, related_name='tareas', to='admon_tareas.etiqueta')),
                ('origen_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='admon_tareas.tarea')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='admon_tareas.seccion')),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='admon_tareas.tablero')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'tareas_tarea',
                'ordering': ('tablero', 'orden', 'ruta_wbs'),
            },
        ),
        migrations.CreateModel(
            name='TareaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=30)),
                ('campo', models.CharField(blank=True, max_length=50)),
                ('valor_ant', models.CharField(blank=True, max_length=500)),
                ('valor_nue', models.CharField(blank=True, max_length=500)),
                ('detalle', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad', to='admon_tareas.tarea')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividad_tarea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad de tarea',
                'verbose_name_plural': 'Actividad de tarea',
                'db_table': 'tareas_tareaactividad',
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='TareaAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('RESP', 'Responsable'), ('COLA', 'Colaborador'), ('REVI', 'Revisor')], default='COLA', max_length=4)),
                ('completado', models.BooleanField(default=False)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('nota_cierre', models.CharField(blank=True, max_length=500)),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_hechas', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='admon_tareas.tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de tarea',
                'verbose_name_plural': 'Asignaciones de tarea',
                'db_table': 'tareas_tareaasignacion',
            },
        ),
        migrations.CreateModel(
            name='TareaComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('editado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_tarea', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='admon_tareas.tarea')),
            ],
            options={
                'verbose_name': 'Comentario de tarea',
                'verbose_name_plural': 'Comentarios de tarea',
                'db_table': 'tareas_tareacomentario',
                'ordering': ('creado_en',),
            },
        ),
        migrations.CreateModel(
            name='TareaDependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FS', 'Fin → Inicio'), ('SS', 'Inicio → Inicio'), ('FF', 'Fin → Fin'), ('SF', 'Inicio → Fin')], default='FS', max_length=2)),
                ('desfase_dias', models.IntegerField(default=0)),
                ('origen', models.CharField(choices=[('PLANEADA', 'Del cronograma'), ('BLOQUEO', 'Reportada en ejecución')], default='PLANEADA', max_length=8)),
                ('motivo', models.TextField(blank=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependencias_creadas', to=settings.AUTH_USER_MODEL)),
                ('predecesora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias_salientes', to='admon_tareas.tarea')),
                ('sucesora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias_entrantes', to='admon_tareas.tarea')),
            ],
            options={
                'verbose_name': 'Dependencia de tarea',
                'verbose_name_plural': 'Dependencias de tarea',
                'db_table': 'tareas_tareadependencia',
            },
        ),
        migrations.AddConstraint(
            model_name='etiqueta',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='uq_etiqueta_empresa_nombre'),
        ),
        migrations.AddConstraint(
            model_name='tablero',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_tablero_codigo'),
        ),
        migrations.AddConstraint(
            model_name='tablero',
            constraint=models.CheckConstraint(condition=models.Q(('es_plantilla', False), ('plantilla_origen__isnull', True), _connector='OR'), name='ck_tablero_plt_origen'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['empresa', 'tablero', 'estado'], name='tareas_tare_empresa_d1d5bd_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['padre'], name='tareas_tare_padre_i_4a5c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['tablero', 'ruta_wbs'], name='tareas_tare_tablero_dab97a_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['origen_ct', 'origen_obj_id'], name='tareas_tare_origen__3d7317_idx'),
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.UniqueConstraint(fields=('empresa', 'folio'), name='uq_tarea_folio'),
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.CheckConstraint(condition=models.Q(('avance__gte', 0), ('avance__lte', 100)), name='ck_tarea_avance'),
        ),
        migrations.AddIndex(
            model_name='tareaactividad',
            index=models.Index(fields=['tarea', 'creado_en'], name='tareas_tare_tarea_i_862713_idx'),
        ),
        migrations.AddIndex(
            model_name='tareaasignacion',
            index=models.Index(fields=['usuario', 'completado'], name='tareas_tare_usuario_e09438_idx'),
        ),
        migrations.AddConstraint(
            model_name='tareaasignacion',
            constraint=models.UniqueConstraint(fields=('tarea', 'usuario'), name='uq_asignacion_tarea_usuario'),
        ),
        migrations.AddIndex(
            model_name='tareacomentario',
            index=models.Index(fields=['tarea', 'creado_en'], name='tareas_tare_tarea_i_773573_idx'),
        ),
        migrations.AddIndex(
            model_name='tareadependencia',
            index=models.Index(fields=['sucesora', 'resuelta'], name='tareas_tare_sucesor_57eafe_idx'),
        ),
        migrations.AddIndex(
            model_name='tareadependencia',
            index=models.Index(fields=['predecesora'], name='tareas_tare_predece_ff19e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='tareadependencia',
            constraint=models.UniqueConstraint(fields=('predecesora', 'sucesora'), name='uq_dependencia'),
        ),
        migrations.AddConstraint(
            model_name='tareadependencia',
            constraint=models.CheckConstraint(condition=models.Q(('predecesora', models.F('sucesora')), _negated=True), name='ck_dependencia_no_self'),
        ),
    ]
