# Generated by Django 5.2.15 on 2026-07-28 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresas', '0011_perfilusuario_foto'),
        ('admon_tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='duracion_horas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TipoTablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_tablero', to='admon_empresas.empresa')),
            ],
            options={
                'verbose_name': 'Tipo de tablero',
                'verbose_name_plural': 'Tipos de tablero',
                'db_table': 'tareas_tipotablero',
                'ordering': ('orden', 'nombre'),
            },
        ),
        # tipo pasa de CharField a FK al catálogo TipoTablero. Se hace como
        # Remove+Add (no Alter) para no fallar en SQL Server convirtiendo el
        # texto viejo a un id numérico. El tipo de tableros previos se pierde
        # (dato de prueba); se recaptura desde el catálogo.
        migrations.RemoveField(
            model_name='tablero',
            name='tipo',
        ),
        migrations.AddField(
            model_name='tablero',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tableros', to='admon_tareas.tipotablero'),
        ),
        migrations.AddConstraint(
            model_name='tipotablero',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='uq_tipotablero_empresa_nombre'),
        ),
    ]
