# Generated by Django 5.2.15 on 2026-07-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_tareas', '0002_tarea_duracion_horas_tipotablero_alter_tablero_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareadependencia',
            name='tipo',
            field=models.CharField(choices=[('FS', 'Fin → Inicio · empieza cuando la otra termina'), ('SS', 'Inicio → Inicio · empiezan al mismo tiempo'), ('FF', 'Fin → Fin · terminan al mismo tiempo'), ('SF', 'Inicio → Fin · termina cuando la otra empieza')], default='FS', max_length=2),
        ),
    ]
