# Generated by Django 5.2.15 on 2026-07-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_tareas', '0004_corregir_bloqueos_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablero',
            name='fecha_fin_base',
            field=models.DateField(blank=True, null=True),
        ),
    ]
