# Generated by Django 5.2.15 on 2026-08-06 00:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_tareas', '0005_tablero_fecha_fin_base'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tablero',
            name='miembros',
            field=models.ManyToManyField(blank=True, db_table='tareas_tablero_miembros', related_name='tableros_invitado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tablero',
            name='visibilidad',
            field=models.CharField(choices=[('TODO', 'Todos los involucrados ven todas las tareas'), ('ASIGNADAS', 'Cada quien ve solo sus tareas asignadas')], default='TODO', max_length=10),
        ),
    ]
