# Generated by Django 5.2.15 on 2026-08-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_tareas', '0006_tablero_miembros_tablero_visibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='es_etapa',
            field=models.BooleanField(default=False, verbose_name='Es etapa'),
        ),
    ]
