# Generated by Django 5.2.15 on 2026-06-16 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admon_empresas', '0005_seed_modulo_ventas'),
        ('admon_inventarios', '0004_remove_detallereceta_insumo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fiscal', models.CharField(max_length=255)),
                ('nombre_comercial', models.CharField(blank=True, max_length=255, null=True)),
                ('rfc', models.CharField(blank=True, max_length=15, verbose_name='RFC / Tax ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('contacto_nombre', models.CharField(blank=True, max_length=100, verbose_name='Atención con')),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('dias_credito', models.PositiveIntegerField(default=0, verbose_name='Días de crédito')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, help_text='0 = sin límite', max_digits=14)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='admon_empresas.empresa')),
                ('moneda_predeterminada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon_empresas.moneda')),
                ('sucursales_acceso', models.ManyToManyField(blank=True, related_name='clientes_permitidos', to='admon_empresas.sucursal')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_fiscal'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=25, unique=True)),
                ('consecutivo', models.IntegerField(default=0)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado'), ('ENTREGADO_PARCIAL', 'Entregado parcial'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20)),
                ('genera_cxc', models.BooleanField(default=True, help_text='Genera cuenta por cobrar al entregar')),
                ('notas', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='admon_ventas.cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_empresas.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_empresas.moneda')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='admon_empresas.sucursal')),
            ],
            options={
                'verbose_name': 'Pedido de venta',
                'verbose_name_plural': 'Pedidos de venta',
                'ordering': ['-fecha_emision', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('cantidad_entregada', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('iva_porcentaje', models.DecimalField(decimal_places=4, default=16, max_digits=7)),
                ('es_retencion', models.BooleanField(default=False)),
                ('impuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon_empresas.impuesto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='admon_ventas.pedido')),
            ],
        ),
    ]
