# Generated by Django 5.2.15 on 2026-06-16 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresas', '0005_seed_modulo_ventas'),
        ('admon_inventarios', '0005_contenidosalidakit_propiedad_existencia_propiedad_and_more'),
        ('admon_ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='tipo_linea',
            field=models.CharField(choices=[('PRODUCTO', 'Producto / consumible'), ('RENTA', 'Renta de equipo')], default='PRODUCTO', max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='origen',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('COTIZACION', 'Desde cotización'), ('CIRUGIA', 'Liquidación de cirugía/kit')], default='MANUAL', max_length=12),
        ),
        migrations.CreateModel(
            name='ComisionPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TECNICO', 'Técnico'), ('DOCTOR', 'Doctor'), ('VENDEDOR', 'Vendedor'), ('OTRO', 'Otro')], default='TECNICO', max_length=10)),
                ('beneficiario', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notas', models.CharField(blank=True, max_length=255, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='admon_ventas.pedido')),
            ],
            options={
                'verbose_name': 'Comisión de pedido',
                'verbose_name_plural': 'Comisiones de pedido',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=25, unique=True)),
                ('consecutivo', models.IntegerField(default=0)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('vigencia', models.DateField(blank=True, help_text='Válida hasta', null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('CONVERTIDA', 'Convertida en pedido'), ('VENCIDA', 'Vencida')], default='BORRADOR', max_length=12)),
                ('notas', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='admon_ventas.cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_empresas.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_empresas.moneda')),
                ('pedido_generado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizacion_origen', to='admon_ventas.pedido')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='admon_empresas.sucursal')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_emision', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_linea', models.CharField(choices=[('PRODUCTO', 'Producto / consumible'), ('RENTA', 'Renta de equipo')], default='PRODUCTO', max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('iva_porcentaje', models.DecimalField(decimal_places=4, default=16, max_digits=7)),
                ('es_retencion', models.BooleanField(default=False)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='admon_ventas.cotizacion')),
                ('impuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon_empresas.impuesto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.producto')),
            ],
        ),
    ]
