# Generated by Django 5.2.15 on 2026-06-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_ventas', '0002_detallepedido_tipo_linea_pedido_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='es_extra',
            field=models.BooleanField(default=False, help_text='Producto agregado al pedido fuera del flujo de cirugía'),
        ),
    ]
