# Generated by Django 5.2.15 on 2026-06-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_ventas', '0003_detallepedido_es_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='constancia_fiscal',
            field=models.FileField(blank=True, null=True, upload_to='constancias/', verbose_name='Constancia de situación fiscal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='regimen_fiscal',
            field=models.CharField(blank=True, max_length=255, verbose_name='Régimen fiscal'),
        ),
    ]
