# Generated by Django 5.2.15 on 2026-06-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_ventas', '0004_cliente_codigo_postal_cliente_constancia_fiscal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='margen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
