# Generated by Django 5.2.15 on 2026-07-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_ventas', '0006_cambiopedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='precio_original',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
