# Generated by Django 5.2.14 on 2026-06-02 19:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=255)),
                ('slug_instancia', models.SlugField(unique=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('token_invitacion', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('registro_completado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fiscal', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('decimales_permitidos', models.PositiveIntegerField(default=2)),
                ('rfc', models.CharField(max_length=20, unique=True)),
                ('autoguardado_intervalo', models.PositiveIntegerField(default=60, help_text='Intervalo en segundos para el autoguardado de documentos.')),
                ('color_primario', models.CharField(choices=[('indigo', 'Indigo Moderno'), ('blue', 'Azul Corporativo'), ('emerald', 'Verde Ecológico'), ('rose', 'Rosa Elegante'), ('slate', 'Gris Profesional')], default='indigo', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='admon_empresas.clientesaas')),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=3)),
                ('simbolo', models.CharField(default='$', max_length=5)),
                ('es_principal', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monedas_empresa', to='admon_empresas.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='moneda_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa_base', to='admon_empresas.moneda'),
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('es_matriz', models.BooleanField(default=False)),
                ('codigo_sucursal', models.CharField(max_length=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='admon_empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('tipo_usuario', models.CharField(choices=[('OWNER', 'Dueño de Empresa'), ('MANAGER', 'Gerente de Sucursal'), ('OPERATOR', 'Operador / Staff')], default='OPERATOR', max_length=20)),
                ('puede_gestionar_usuarios', models.BooleanField(default=False, help_text='Permite al dueño crear y editar usuarios de su propia empresa.')),
                ('invitacion_aceptada', models.BooleanField(default=False)),
                ('empresa_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon_empresas.empresa')),
                ('empresas', models.ManyToManyField(related_name='empleados', to='admon_empresas.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('sucursal_defecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon_empresas.sucursal')),
                ('sucursales', models.ManyToManyField(blank=True, related_name='usuarios_permitidos', to='admon_empresas.sucursal')),
            ],
        ),
    ]
