# Generated by Django 5.2.15 on 2026-06-13 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: IVA 16%, Retención 6.25%, Exento', max_length=60)),
                ('tasa', models.DecimalField(decimal_places=4, default=0, help_text='Porcentaje. Ej: 16, 8, 0, 6.25', max_digits=7)),
                ('tipo_factor', models.CharField(choices=[('TASA', 'Tasa'), ('EXENTO', 'Exento')], default='TASA', max_length=10)),
                ('es_retencion', models.BooleanField(default=False, help_text='Si se marca, resta del total en vez de sumar.')),
                ('clave_sat', models.CharField(blank=True, max_length=10, null=True)),
                ('es_default', models.BooleanField(default=False, help_text='Se aplica cuando un producto no tiene impuesto asignado.')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuestos', to='admon_empresas.empresa')),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
