# Generated by Django 5.2.15 on 2026-06-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresas', '0006_seed_modulo_cirugias'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='isotipo',
            field=models.ImageField(blank=True, help_text='Solo el emblema (cuadrado), para vistas compactas/favicon.', null=True, upload_to='isotipos/'),
        ),
    ]
