# Generated by Django 5.2.15 on 2026-06-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresas', '0008_seccionocultausuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='tema_error',
            field=models.CharField(choices=[('robot', 'Robot (formal / médico)'), ('alien', 'Alien (informal / divertido)')], default='robot', help_text='Estilo de la página amigable que se muestra ante errores o mantenimiento.', max_length=10, verbose_name='Tema de página de error'),
        ),
    ]
