# Generated by Django 5.2.15 on 2026-07-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresas', '0009_empresa_tema_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email_contador',
            field=models.EmailField(blank=True, help_text='A dónde se avisa cuando faltan complementos de pago (REP) por generar.', max_length=254, null=True, verbose_name='Correo del contador'),
        ),
    ]
