# Generated by Django 5.2.15 on 2026-06-16 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admon_compras', '0002_detalleordencompra_es_retencion_and_more'),
        ('admon_empresas', '0002_impuesto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(help_text='Folio de la factura del proveedor', max_length=50)),
                ('uuid_cfdi', models.CharField(blank=True, help_text='UUID del CFDI (opcional)', max_length=40, null=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de pago'), ('PARCIAL', 'Pago parcial'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=12)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_proveedor', to='admon_empresas.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_empresas.moneda')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='admon_compras.ordencompra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_compras.proveedor')),
                ('registrada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura de proveedor',
                'verbose_name_plural': 'Facturas de proveedor',
                'ordering': ['-fecha_emision', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('clave_sat', models.CharField(blank=True, help_text='Clave SAT forma de pago (futuro CFDI)', max_length=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to='admon_empresas.empresa')),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EGRESO', 'Egreso (pago a proveedor)'), ('INGRESO', 'Ingreso (cobro a cliente)')], default='EGRESO', max_length=8)),
                ('folio', models.CharField(blank=True, max_length=20)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, default=0, help_text='Total del pago en su propia moneda (suma de aplicaciones)', max_digits=14)),
                ('cuenta_banco', models.CharField(blank=True, help_text='Cuenta/banco de donde salió (informativo)', max_length=100, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='admon_empresas.empresa')),
                ('metodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_finanzas.metodopago')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_empresas.moneda')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_compras.proveedor')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AplicacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, help_text='En la moneda de la factura', max_digits=14)),
                ('tipo_cambio', models.DecimalField(decimal_places=6, default=1, help_text='Moneda_pago por 1 de moneda_factura (1 si misma moneda)', max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='admon_finanzas.facturaproveedor')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='admon_finanzas.pago')),
            ],
        ),
    ]
