# Generated by Django 5.2.15 on 2026-06-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproveedor',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cfdi/facturas/pdf/'),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='archivo_xml',
            field=models.FileField(blank=True, null=True, upload_to='cfdi/facturas/xml/'),
        ),
        migrations.AddField(
            model_name='pago',
            name='complemento_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cfdi/complementos/pdf/'),
        ),
        migrations.AddField(
            model_name='pago',
            name='complemento_xml',
            field=models.FileField(blank=True, null=True, upload_to='cfdi/complementos/xml/'),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_complemento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='uuid_complemento',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
