# Generated by Django 5.2.15 on 2026-06-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_finanzas', '0002_facturaproveedor_archivo_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(help_text='Folio interno de la cuenta por cobrar', max_length=25)),
                ('uuid_cfdi', models.CharField(blank=True, help_text='UUID del CFDI emitido (opcional)', max_length=40, null=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de cobro'), ('PARCIAL', 'Cobro parcial'), ('PAGADA', 'Cobrada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=12)),
                ('notas', models.TextField(blank=True, null=True)),
                ('archivo_xml', models.FileField(blank=True, null=True, upload_to='cfdi/cobrar/xml/')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='cfdi/cobrar/pdf/')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Factura de cliente',
                'verbose_name_plural': 'Facturas de cliente',
                'ordering': ['-fecha_emision', '-id'],
            },
        ),
    ]
