# Generated by Django 5.2.15 on 2026-06-16 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresas', '0005_seed_modulo_ventas'),
        ('admon_finanzas', '0003_facturacliente'),
        ('admon_ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_ventas.cliente'),
        ),
        migrations.AlterField(
            model_name='aplicacionpago',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='admon_finanzas.facturaproveedor'),
        ),
        migrations.AddField(
            model_name='facturacliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_ventas.cliente'),
        ),
        migrations.AddField(
            model_name='facturacliente',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_cliente', to='admon_empresas.empresa'),
        ),
        migrations.AddField(
            model_name='facturacliente',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_empresas.moneda'),
        ),
        migrations.AddField(
            model_name='facturacliente',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='admon_ventas.pedido'),
        ),
        migrations.AddField(
            model_name='facturacliente',
            name='registrada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aplicacionpago',
            name='factura_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='admon_finanzas.facturacliente'),
        ),
    ]
