# Generated by Django 5.2.15 on 2026-06-22 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresas', '0007_empresa_isotipo'),
        ('admon_finanzas', '0004_pago_cliente_alter_aplicacionpago_factura_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('clasificacion', models.CharField(choices=[('VENTA', 'Gastos de venta'), ('ADMIN', 'Gastos de administración'), ('FINANCIERO', 'Gastos financieros'), ('OTRO', 'Otros gastos')], default='ADMIN', max_length=12)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_gasto', to='admon_empresas.empresa')),
            ],
            options={
                'verbose_name': 'Categoría de gasto',
                'verbose_name_plural': 'Categorías de gasto',
                'ordering': ['clasificacion', 'nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('proveedor_nombre', models.CharField(blank=True, help_text='A quién se le pagó', max_length=160)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Importe sin IVA', max_digits=14)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('referencia', models.CharField(blank=True, max_length=80)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='gastos/')),
                ('uuid_cfdi', models.CharField(blank=True, max_length=40, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='admon_finanzas.categoriagasto')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_registrados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='admon_empresas.empresa')),
                ('metodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admon_finanzas.metodopago')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='admon_empresas.sucursal')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
