# Generated by Django 5.2.15 on 2026-06-22 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresas', '0007_empresa_isotipo'),
        ('admon_finanzas', '0005_categoriagasto_gasto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidaResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naturaleza', models.CharField(choices=[('OTRO_INGRESO', 'Otros ingresos'), ('OTRO_EGRESO', 'Otros gastos (no operativos)'), ('IMPUESTO', 'Impuestos')], max_length=14)),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, default=0, help_text='Importe positivo; el signo lo da la naturaleza', max_digits=14)),
                ('referencia', models.CharField(blank=True, max_length=80)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas_resultado', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_resultado', to='admon_empresas.empresa')),
            ],
            options={
                'verbose_name': 'Partida de resultado',
                'verbose_name_plural': 'Partidas de resultado',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
