# Generated by Django 5.2.15 on 2026-06-22 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_empresas', '0007_empresa_isotipo'),
        ('admon_finanzas', '0006_partidaresultado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteSAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=40)),
                ('direccion', models.CharField(choices=[('EMITIDO', 'Emitido (venta)'), ('RECIBIDO', 'Recibido (compra/gasto)')], max_length=8)),
                ('tipo', models.CharField(blank=True, help_text='I/E/P/N (ingreso, egreso, pago, nómina)', max_length=2)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('rfc_emisor', models.CharField(blank=True, max_length=15)),
                ('nombre_emisor', models.CharField(blank=True, max_length=200)),
                ('rfc_receptor', models.CharField(blank=True, max_length=15)),
                ('nombre_receptor', models.CharField(blank=True, max_length=200)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('serie_folio', models.CharField(blank=True, max_length=60)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes_sat', to='admon_empresas.empresa')),
            ],
            options={
                'verbose_name': 'Comprobante SAT',
                'verbose_name_plural': 'Comprobantes SAT',
                'ordering': ['-fecha', '-id'],
                'unique_together': {('empresa', 'uuid')},
            },
        ),
    ]
