# Generated by Django 5.2.15 on 2026-06-23 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_finanzas', '0007_comprobantesat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CfdiCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=40)),
                ('serie_folio', models.CharField(blank=True, default='', max_length=60)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('archivo_xml', models.FileField(blank=True, null=True, upload_to='cfdi/cobrar/xml/')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='cfdi/cobrar/pdf/')),
                ('cargado_en', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfdis', to='admon_finanzas.facturacliente')),
            ],
            options={
                'verbose_name': 'CFDI de cliente',
                'verbose_name_plural': 'CFDI de cliente',
                'ordering': ['fecha', 'id'],
                'unique_together': {('factura', 'uuid')},
            },
        ),
    ]
