# Generated by Django 5.2.15 on 2026-06-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_finanzas', '0008_cfdicliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacliente',
            name='retenciones',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ISR/IVA retenidos (restan del total). Servicios.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='facturacliente',
            name='impuestos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='IVA trasladado (suma al total)', max_digits=14),
        ),
    ]
