# Generated by Django 5.2.15 on 2026-06-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_finanzas', '0009_facturacliente_retenciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfdicliente',
            name='retenciones',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ISR/IVA retenidos de este CFDI', max_digits=14),
        ),
        migrations.AddField(
            model_name='cfdicliente',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='cfdicliente',
            name='traslados',
            field=models.DecimalField(decimal_places=2, default=0, help_text='IVA trasladado de este CFDI', max_digits=14),
        ),
    ]
