# Generated by Django 5.2.15 on 2026-06-30 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_finanzas', '0011_backfill_cfdi_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacionpago',
            name='cfdi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='admon_finanzas.cfdicliente'),
        ),
    ]
