# Generated by Django 5.2.15 on 2026-06-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_finanzas', '0012_aplicacionpago_cfdi'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfdicliente',
            name='enviado_en',
            field=models.DateTimeField(blank=True, help_text='Cuándo se envió este CFDI al cliente por correo', null=True),
        ),
        migrations.AddField(
            model_name='facturacliente',
            name='enviado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
