# Generated by Django 5.2.15 on 2026-07-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_finanzas', '0013_cfdicliente_enviado_en_facturacliente_enviado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='pagos/comprobantes/'),
        ),
    ]
