# Generated by Django 5.2.15 on 2026-07-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_finanzas', '0014_pago_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfdicliente',
            name='metodo_pago',
            field=models.CharField(blank=True, default='', help_text='PUE (pago en una exhibición) o PPD (en parcialidades/diferido, requiere REP)', max_length=3),
        ),
    ]
