# Generated by Django 5.2.15 on 2026-07-15 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_finanzas', '0015_cfdicliente_metodo_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnticipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('uuid_cfdi', models.CharField(blank=True, default='', help_text='UUID del CFDI de anticipo (lo emite el contador)', max_length=40)),
                ('serie_folio', models.CharField(blank=True, default='', max_length=60)),
                ('archivo_xml', models.FileField(blank=True, null=True, upload_to='cfdi/anticipos/xml/')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='cfdi/anticipos/pdf/')),
                ('notas', models.CharField(blank=True, default='', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anticipos', to='admon_finanzas.facturacliente')),
            ],
            options={
                'verbose_name': 'Anticipo de cliente',
                'verbose_name_plural': 'Anticipos de cliente',
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
