# Generated by Django 5.2.15 on 2026-07-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_finanzas', '0016_anticipocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='complemento_enviado_en',
            field=models.DateTimeField(blank=True, help_text='Cuándo se envió el REP al cliente por correo', null=True),
        ),
    ]
