# Generated by Django 5.2.15 on 2026-06-17 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admon_empresas', '0006_seed_modulo_cirugias'),
        ('admon_inventarios', '0005_contenidosalidakit_propiedad_existencia_propiedad_and_more'),
        ('admon_ventas', '0002_detallepedido_tipo_linea_pedido_origen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('celular', models.CharField(blank=True, max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('rfc', models.CharField(blank=True, max_length=15)),
                ('razon_social', models.CharField(blank=True, max_length=255)),
                ('cedula', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctores', to='admon_empresas.empresa')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitales', to='admon_empresas.empresa')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCirugia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=25, unique=True)),
                ('consecutivo', models.IntegerField(default=0)),
                ('paciente', models.CharField(blank=True, help_text='Referencia del paciente (no datos sensibles)', max_length=255)),
                ('fecha_cirugia', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('SURTIDA', 'Surtida (material enviado)'), ('LIQUIDADA', 'Liquidada (pedido generado)'), ('CANCELADA', 'Cancelada')], default='SOLICITADA', max_length=12)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_ventas.cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cirugias_creadas', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_cirugias.doctor')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admon_empresas.empresa')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_cirugias.hospital')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirugias', to='admon_ventas.pedido')),
                ('salidas', models.ManyToManyField(blank=True, related_name='solicitudes_cirugia', to='admon_inventarios.salidakit')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cirugias', to='admon_empresas.sucursal')),
            ],
            options={
                'verbose_name': 'Solicitud de cirugía',
                'verbose_name_plural': 'Solicitudes de cirugía',
                'ordering': ['-fecha_cirugia', '-id'],
            },
        ),
    ]
