# Generated by Django 5.2.15 on 2026-06-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_cirugias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcirugia',
            name='estado',
            field=models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('SURTIDA', 'Surtida (material enviado)'), ('POR_FACTURAR', 'Por facturar (finalizada, pendiente de pedido)'), ('LIQUIDADA', 'Liquidada (pedido generado)'), ('CANCELADA', 'Cancelada')], default='SOLICITADA', max_length=12),
        ),
    ]
