# Generated by Django 5.2.15 on 2026-07-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_cirugias', '0002_alter_solicitudcirugia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcirugia',
            name='estado',
            field=models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('SURTIDA', 'Surtida (material enviado)'), ('RETORNADA', 'Regresada (pendiente de finalizar)'), ('POR_FACTURAR', 'Por facturar (finalizada, pendiente de pedido)'), ('LIQUIDADA', 'Liquidada (pedido generado)'), ('CANCELADA', 'Cancelada')], default='SOLICITADA', max_length=12),
        ),
    ]
