# Generated by Django 5.2.15 on 2026-07-16 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_cirugias', '0003_alter_solicitudcirugia_estado'),
        ('admon_inventarios', '0012_alter_salidakit_instancia_kit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SueltoCirugia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.producto')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sueltos', to='admon_cirugias.solicitudcirugia')),
            ],
            options={
                'verbose_name': 'Material suelto de cirugía',
                'verbose_name_plural': 'Material suelto de cirugía',
                'ordering': ['id'],
            },
        ),
    ]
