# Generated by Django 5.2.15 on 2026-07-16 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admon_cirugias', '0004_sueltocirugia'),
        ('admon_inventarios', '0012_alter_salidakit_instancia_kit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sueltocirugia',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.lote'),
        ),
        migrations.AddField(
            model_name='sueltocirugia',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.numeroserie'),
        ),
        migrations.AddField(
            model_name='sueltocirugia',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admon_inventarios.ubicacion'),
        ),
    ]
